version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "4816:4816"
      - "2657:2657"

networks:
  default:
    external: true
    name: network8
